### ISSUE TITLE
Meet errors when running

### ISSUE THREAD

**Issue by Homiejc** [arrival-ltd/catalyst-rl-tutorial#14]
Hello, your work about the peg-in-hole with the reinforcement is excellent!
I am so happy to have a tutorial like this.
Unfortunately, I had some trouble when running your example, the details are as below:
```
(python:46275): Gtk-WARNING **: 16:25:05.465: Theme parsing error: gtk.css:8008:70: The :focused pseudo-class is deprecated. Use : focus instead.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
I had tried so many times but could not solve the problem
and my device is Ubuntu20.04(CPU) with the conda environment as below
```
python=3.6.5
torch=1.3.1
torchivision=0.4.2
catalyst=20.9
catalyst-rl=20.3
```
Thank you for your time. And I'm looking forward to your reply!

**Comment by fedor-chervinskii** [comment]
Hi @Homiejc! One of the authors here. I'm happy you found our tutorial useful!

Unfortunately, it's quite some time has passed since we released the code so I assume some dependencies can be outdated. I have some time to look into it now, and maybe replace some dependencies with more up-to-date libraries.

To help me better figure out which libraries to use - could you provide more details on a project you have in mind right now? Or are you simply interested in following the tutorial for learning purposes? - In this case, what primarily are you interested in - robotics / Computer Vision part / Reinforcement Learning? Are you interested in learning specific tools like CoppelliaSim or Catalyst?

Understanding your motivation for using this project will help me fix it!

Thanks!

Fedor "Theo" Chervinskii

**Comment by Homiejc** [comment]
Hi Fedor-Chervinskii! I am so appreciative that I can get your relay since this project has been released for a long long time. Thank you for your help again！

I am a post-student major in robotics and very interested in the peg-in-hole problem. There is no doubt that reinforcement learning is a good way to solve this problem and your work has proven that. I am so excited by the performance of your work. I hope I can learn more about robotics and reinforcement by following your tutorial and eventually build my project to solve the problem as you did. And, yes, I am interested in learning reinforcement learning tools like CoppelliaSim and Catalyst as they provide enough resources to help me study.

Thank you!

ZY H

**Comment by mechanics-chenshuo** [comment]
Hello, your research on assembly is very useful to me! May I ask that I also encountered the above problem:terminate called after throwing an instance of 'std::bad_alloc'，abandoned the core dump
May I ask what the reason is? I have tried a lot of methods, but I still report an error. The example of the Catalist-RL package is that CoppeliaSim software can run, and the example is that the Catalist-RL-tutorial does not run. Your reply will be very important to me. Thank you for your thoughts and suggestions

**Comment by mechanics-chenshuo** [comment]
@Homiejc 
Hello, classmate, have you solved your problem? How to solve it

**Comment by Homiejc** [comment]
Sorry, I did not solve that problem either. I think this problem happened because the incompatible between the  version 
 of the tensorflow and the Catalist-RL.Catalist-RL is too old for most published python-packages.

**Comment by Homiejc** [comment]
maybe you can try the stable baseline 3 as the training part. and you can take the code from this resource as an example to rebuild the project based on sb3 and coppelisim. That works for me. and the simulated scenario provided by this resource works well

**Comment by mechanics-chenshuo** [comment]
@Homiejc Thank you for your reply, may I ask if you have time to provide some technical guidance? In fact, I am just getting started and want to repeat an example of an assembly scene that can run through, but I am not very proficient in reinforcement learning. If you are convenient, you can add wechat to chat: 17854838321, thank you very much

**Comment by ccccccc-lab** [comment]
@mechanics-chenshuo @Homiejc Hello,classmate,have you solved your problem?I also meet this problem.If i don‘t use the stable baseline 3,is there a solution？
